package com.github.diwakar1988.junket.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.diwakar1988.junket.db.dao.Review;
import com.github.diwakar1988.junket.db.dao.FavoriteVenue;

import com.github.diwakar1988.junket.db.dao.ReviewDao;
import com.github.diwakar1988.junket.db.dao.FavoriteVenueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reviewDaoConfig;
    private final DaoConfig favoriteVenueDaoConfig;

    private final ReviewDao reviewDao;
    private final FavoriteVenueDao favoriteVenueDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reviewDaoConfig = daoConfigMap.get(ReviewDao.class).clone();
        reviewDaoConfig.initIdentityScope(type);

        favoriteVenueDaoConfig = daoConfigMap.get(FavoriteVenueDao.class).clone();
        favoriteVenueDaoConfig.initIdentityScope(type);

        reviewDao = new ReviewDao(reviewDaoConfig, this);
        favoriteVenueDao = new FavoriteVenueDao(favoriteVenueDaoConfig, this);

        registerDao(Review.class, reviewDao);
        registerDao(FavoriteVenue.class, favoriteVenueDao);
    }
    
    public void clear() {
        reviewDaoConfig.getIdentityScope().clear();
        favoriteVenueDaoConfig.getIdentityScope().clear();
    }

    public ReviewDao getReviewDao() {
        return reviewDao;
    }

    public FavoriteVenueDao getFavoriteVenueDao() {
        return favoriteVenueDao;
    }

}
