package com.github.diwakar1988.junket.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAVORITE_VENUE".
 */
public class FavoriteVenue {

    private String venueId;
    private String json;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FavoriteVenue() {
    }

    public FavoriteVenue(String venueId) {
        this.venueId = venueId;
    }

    public FavoriteVenue(String venueId, String json, java.util.Date date) {
        this.venueId = venueId;
        this.json = json;
        this.date = date;
    }

    public String getVenueId() {
        return venueId;
    }

    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
